{
 "title": "Account statistics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": "SHOW TAG VALUES WITH KEY = \"scan_type\""
   }
  ]
 },
 "panels": [
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Scanned bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT mean(\"scanned_bytes\") FROM \"scan_completed\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "scanned_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Scan duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT mean(\"scan_duration\") FROM \"scan_completed\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "scan_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scan_type", "operator": "=~", "value": "/^$Type$/" }
     ]
    },
    {
     "alias": "Binary bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT mean(\"scanned_bytes\") FROM \"scan_completed\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "binary_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Components",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT mean(\"component_count\") FROM \"scan_completed\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "component_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scan_type", "operator": "=~", "value": "/^$Type$/" }
     ]
    },
    {
     "alias": "Versionless components",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT mean(\"versionless_component_count\") FROM \"scan_completed\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "versionless_component_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scanned bytes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT mean(*) AS \" \" FROM \"scan_metadata\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "scanned_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Scanned bytes" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "scan_completed",
     "select": [
      [
       { "params": [ "binary_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Binary bytes" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "scan_completed",
     "select": [
      [
       { "params": [ "infoleak_scanned_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Infoleak bytes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mimetypes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "scan_metadata",
     "query": "SELECT mean(*) AS \" \" FROM \"scan_metadata\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scan_type", "operator": "=~", "value": "/^$Type$/" }
     ]
    }
   ]
  },
  {
   "title": "Uploaded bytes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT sum(\"binary_bytes\") FROM \"scan_completed\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "binary_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scan_type", "operator": "=~", "value": "/^$Type$/" }
     ]
    }
   ]
  },
  {
   "title": "Found components",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT sum(\"component_count\") FROM \"scan_completed\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "component_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scanned bytes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT sum(\"scanned_bytes\") FROM \"scan_completed\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "scanned_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unversioned components",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scan_completed",
     "query": "SELECT sum(\"versionless_component_count\") FROM \"scan_completed\" WHERE \"scan_type\" =~ /^$Type$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "versionless_component_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}